services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pact
      POSTGRES_PASSWORD: pact
      POSTGRES_DB: pact
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - umbrel_main_network

  pact-broker:
    image: pactfoundation/pact-broker:latest
    environment:
      PACT_BROKER_DATABASE_USERNAME: pact
      PACT_BROKER_DATABASE_PASSWORD: pact
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pact
      PACT_BROKER_PORT: 9292
      PACT_BROKER_BASIC_AUTH_USERNAME: admin
      PACT_BROKER_BASIC_AUTH_PASSWORD: admin
      PACT_BROKER_LOG_LEVEL: DEBUG
    ports:
      - "9292:9292"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - umbrel_main_network

volumes:
  postgres_data:

networks:
  umbrel_main_network:
    external: true