services:
  app_proxy:
    environment:
      APP_HOST: mrbrown-pact-broker_server_1
      APP_PORT: 9292
      PROXY_AUTH_ADD: "false"
    restart: on-failure
    depends_on:
      - server
    networks:
      - umbrel_main_network

  server:
    image: pactfoundation/pact-broker:latest
    user: "1000:1000"
    init: true
    environment:
      PACT_BROKER_DATABASE_USERNAME: pact
      PACT_BROKER_DATABASE_PASSWORD: pact
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pact
      PACT_BROKER_PORT: 9292
      PACT_BROKER_BASIC_AUTH_USERNAME: admin
      PACT_BROKER_BASIC_AUTH_PASSWORD: admin
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: "http,https"
      PACT_BROKER_WEBHOOK_HOST_WHITELIST: "umbrel.local:8085,192.168.1.0/24"
      PACT_BROKER_WEBHOOK_HTTP_METHOD_WHITELIST: "POST,PUT,GET"
      PACT_BROKER_LOG_LEVEL: DEBUG
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - umbrel_main_network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pact
      POSTGRES_PASSWORD: pact
      POSTGRES_DB: pact
    volumes:
      - ${APP_DATA_DIR}/postgres:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true