services:
  app_proxy:
    image: nginx:1.17-alpine
    environment:
      APP_HOST: mrbrown-pact-broker_1
      APP_PORT: 9292
    volumes:
      - ${APP_DATA_DIR}/nginx:/etc/nginx
    restart: on-failure
    user: "1000:1000"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: pact
      POSTGRES_PASSWORD: pact
      POSTGRES_DB: pact
    volumes:
      - ${APP_DATA_DIR}/postgres:/var/lib/postgresql/data
    restart: on-failure
    user: "1000:1000"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pact"]
      interval: 10s
      timeout: 5s
      retries: 5

  pact-broker:
    image: pactfoundation/pact-broker:latest
    environment:
      PACT_BROKER_DATABASE_USERNAME: pact
      PACT_BROKER_DATABASE_PASSWORD: pact
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pact
      PACT_BROKER_PORT: 9292
      PACT_BROKER_BASIC_AUTH_USERNAME: admin
      PACT_BROKER_BASIC_AUTH_PASSWORD: admin
      PACT_BROKER_LOG_LEVEL: INFO
      RACK_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    user: "1000:1000"
 