services:
  app_proxy:
    image: nginx:1.17-alpine
    environment:
      APP_HOST: mrbrown-pact-broker_1
      APP_PORT: 9292
    volumes:
      - ${APP_DATA_DIR}/nginx:/etc/nginx:ro
    restart: on-failure
    user: "1000:1000"
    networks:
      - default

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pact
      POSTGRES_PASSWORD: pact
      POSTGRES_DB: pact
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Change to named volume
    restart: on-failure
    user: postgres  # Make sure to use the postgres user
    networks:
      - default

  pact-broker:
    image: pactfoundation/pact-broker:latest
    environment:
      PACT_BROKER_DATABASE_USERNAME: pact
      PACT_BROKER_DATABASE_PASSWORD: pact
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pact
      PACT_BROKER_PORT: 9292
      PACT_BROKER_BASIC_AUTH_USERNAME: admin
      PACT_BROKER_BASIC_AUTH_PASSWORD: admin
      PACT_BROKER_LOG_LEVEL: DEBUG
    depends_on:
      - postgres
    restart: on-failure
    user: "1000:1000"
    networks:
      - default

networks:
  default:
    name: umbrel_main_network
    external: true
 