services:
  app_proxy:
    environment:
      APP_HOST: mrbrown-cypress_dashboard_1
      APP_PORT: 9293
    restart: on-failure
    networks:
      - default
      - umbrel_main_network

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
      MONGODB_DATABASE: "sorry-cypress"
    ports:
      - 9294:4000
    depends_on:
      - mongo
    restart: on-failure
    networks:
      - default

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: "http://192.168.1.128:9294/graphql"
      PORT: "9293"
    depends_on:
      - api
    restart: on-failure
    networks:
      - default

  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: "http://192.168.1.128:9293"
      EXECUTION_DRIVER: "../execution/mongo/driver"
      MONGODB_URI: "mongodb://mongo:27017"
      MONGODB_DATABASE: "sorry-cypress"
      SCREENSHOTS_DRIVER: "../screenshots/minio.driver"
      MINIO_ACCESS_KEY: "sorry-cypress"
      MINIO_SECRET_KEY: "sorry-cypress"
      MINIO_ENDPOINT: "storage"
      MINIO_PORT: "9000"
      MINIO_BUCKET: "sorry-cypress"
      MINIO_USESSL: "false"
    restart: on-failure
    ports:
      - 9295:1234
    volumes:
      - ${APP_DATA_DIR}/data/director:/data
    networks:
      - default

  mongo:
    image: mongo:4.4
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/mongo:/data/db
    networks:
      - default

  storage:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    environment:
      MINIO_ACCESS_KEY: "sorry-cypress"
      MINIO_SECRET_KEY: "sorry-cypress"
    command: server /data
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/minio:/data
    networks:
      - default

  createbuckets:
    image: minio/mc:RELEASE.2021-06-13T17-48-22Z
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://storage:9000 sorry-cypress sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc policy set public myminio/sorry-cypress;
      exit 0;
      "
    networks:
      - default

networks:
  default:
  umbrel_main_network:
    external: true